export const GET_BOARD_LOADING = 'GET_BOARD_LOADING'
export const GET_BOARD_SUCCESS = 'GET_BOARD_SUCCESS'
export const GET_BOARD_ERROR = 'GET_BOARD_ERROR'

export const GET_CARDS = 'GET_CARDS'
export const DELETE_CARD_SUCCESS = 'DELETE_CARD_SUCCESS'
export const DELETE_CARD_ERROR = 'DELETE_CARD_ERROR'
export const CHANGE_CARD_SUCCESS = 'CHANGE_CARD_SUCCESS'
export const CHANGE_CARD_ERROR = 'CHANGE_CARD_ERROR'
