export const FETCH_ERROR = 'FETCH_ERROR'
export const FETCH_LOADING = 'FETCH_LOADING'

export const SET_USER_FILTER = 'SET_USER_FILTER'
export const SET_TAB_FILTER = 'SET_TAB_FILTER'

export const GET_BOARD_SUCCESS = 'GET_BOARD_SUCCESS'
export const GET_BOARD_FILTER = 'GET_BOARD_FILTER'

export const GET_TAB_CARDS = 'GET_TAB_CARDS'
export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS'
export const CHANGE_CARD_SUCCESS = 'CHANGE_CARD_SUCCESS'
export const DELETE_CARD_SUCCESS = 'DELETE_CARD_SUCCESS'

export const GET_PAYER_BUDGET = 'GET_PAYER_BUDGET'

export const GET_TRAVEL_SUCCESS = 'GET_TRAVEL_SUCCESS'
export const CHANGE_TRAVEL_SUCCESS = 'CHANGE_TRAVEL_SUCCESS'
