export const FETCH_ERROR = 'FETCH_ERROR'
export const FETCH_LOADING = 'FETCH_LOADING'

export const SET_USER_FILTER = 'SET_USER_FILTER'
export const SET_TAB_FILTER = 'SET_TAB_FILTER'
export const SET_HISTORY_FILTER = 'SET_HISTORY_FILTER'

export const GET_BOARD_SUCCESS = 'GET_BOARD_SUCCESS'
export const GET_BOARD_FILTER = 'GET_BOARD_FILTER'

export const GET_TAB_CARDS = 'GET_TAB_CARDS'
export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS'
export const CHANGE_CARD_SUCCESS = 'CHANGE_CARD_SUCCESS'
export const DELETE_CARD_SUCCESS = 'DELETE_CARD_SUCCESS'
export const GET_CARDS_FILTER = 'GET_CARDS_FILTER'

export const GET_PAYER_BUDGET = 'GET_PAYER_BUDGET'

export const GET_TRAVEL_SUCCESS = 'GET_TRAVEL_SUCCESS'
export const CHANGE_TRAVEL_SUCCESS = 'CHANGE_TRAVEL_SUCCESS'
export const CREATE_TRAVEL_SUCCESS = 'CREATE_TRAVEL_SUCCESS'
export const DELETE_TRAVEL_SUCCESS = 'DELETE_TRAVEL_SUCCESS'

export const GET_USER_LOADING = 'GET_USER_LOADING'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_ERROR = 'GET_USER_ERROR'

export const UPDATE_USER_LOADING = 'UPDATE_USER_LOADING'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const USER_AVATAR_LOADING = 'USER_AVATAR_LOADING'
export const USER_AVATAR_ERROR = 'USER_AVATAR_ERROR'

export const GET_TRAVELS_FILTER = 'GET_TRAVELS_FILTER'

export const SEARCH_CONTACT_LOADING = 'SEARCH_CONTACT_LOADING'
export const SEARCH_CONTACT_SUCCESS = 'SEARCH_CONTACT_SUCCESS'
export const SEARCH_CONTACT_ERROR = 'SEARCH_CONTACT_ERROR'

export const UPDATE_CONTACTS_ERROR = 'UPDATE_CONTACTS_ERROR'
export const UPDATE_CONTACTS_SUCCESS = 'UPDATE_CONTACTS_SUCCESS'

export const CLEAR_CONTACTS_SEARCH = 'CLEAR_CONTACTS_SEARCH'
export const CLEAR_ERROR_SEARCH = 'CLEAR_ERROR_SEARCH'

export const REGISTRATION_LOADING = 'REGISTRATION_LOADING'
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS'
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR'

export const LOGIN_LOADING = 'LOGIN_LOADING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_ERROR = 'LOGOUT_ERROR'
export const UNAUTHORIZED = 'UNAUTHORIZED'
